media_folder: static/content/uploads
#public_folder: /img/uploads
backend:
  name: git-gateway
  repo: opf/open-budget-portal-source

  api_root: https://git.spending.gov.ua/api/v4
  base_url: https://git.spending.gov.ua


  branch: develop
  accept_roles: #optional - accepts all users if left out
    - admin
    - cms
###################################

collections:
  - label: 'Головна сторінка'
    name: "mainPage"
    file: "/main/mainPage.json"
    format: json
    fields:
      - label: "Про компанію"
          name: "aboutCompany"
          widget: object
          format: json
          fields:
            - { label: "Опис(блок_1)", name: "titleText", widget: string, required: true }
            - { label: "Опис(блок_1)_en", name: "titleText_en", widget: string, required: true }
            - { label: "Опис(блок_2)", name: "textP1", widget: string, required: true }
            - { label: "Опис(блок_2)_en", name: "textP1_en", widget: string, required: true }
            - label: "Опис(блок_3)"
                name: "list"
                widget: object
                format: json
                required: true
                fields:
                  - { label: "role", name: "role", widget: string, required: true, default: "role" }
                  - { label: "Заголовок", name: "title", widget: string, required: true }
                  - label: "список"
                      name: "items"
                      widget: "list"
                      field: { widget: string }
            - label: "Опис(блок_3)_en"
                name: "list_en"
                widget: object
                format: json
                required: true
                fields:
                  - { label: "role", name: "role", widget: string, required: true, default: "role" }
                  - { label: "Заголовок", name: "title", widget: string, required: true }
                  - label: "список"
                      name: "items"
                      widget: "list"
                      field: { widget: string }
            - { label: "Опис(блок_4)", name: "textP2", widget: string, required: true }
            - { label: "Опис(блок_4)_en", name: "textP2_en", widget: string, required: true }
      - label: "Проекти"
          name: "mainPageProjects"
          widget: "list"
          fields:
            - { label: "link", name: "link", widget: string, required: true }
            - { label: "Назва", name: "title", widget: string, required: true }
            - { label: "Назва_en", name: "title_en", widget: string, required: true }
            - { label: "Опис", name: "content", widget: string, required: true }
            - { label: "Опис_en", name: "content_en", widget: string, required: true }
            - label: "Зображення"
                  name: "image"
                  widget: object
                  fields:
                    - { label: "Завантажити", name: "src", widget: image }
                    - { label: "Alt", name: "alt", widget: string, default: "img" }
                    - { label: "Alt_eng", name: "alt_eng", widget: string, default: "img" }
 ###################################
